apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: udacity-reverse-proxy
spec:
  replicas: 1
  selector:
  matchLabels:
    app: udacity-reverse-proxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: zxa011023/udacity-reverse-proxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8083
      restartPolicy: Always