apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: udacity-reverse-proxy
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    service: reverseproxy